### ISSUE TITLE
Storage node panic while setting maintenance status

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#1678]
## Expected Behavior
Storage node in status maintenance

## Current Behavior
Some times CLI command 
`admin@glagoli:~$ sudo neofs-cli --endpoint 127.0.0.1:8091 -w /etc/neofs/storage/wallet.json control set-status --status maintenance`
return error:
`rpc error: rpc error: code = Unavailable desc = error reading from server: EOF`
See attached log: [maintenance panic log.txt](https://github.com/nspcc-dev/neofs-node/files/9306840/maintenance.panic.log.txt)

## Steps to Reproduce (for bugs)
The issue does not reproduce on every run.
1. SSH to node
2. Try to set maintenance mode following this command `admin@glagoli:~$ sudo neofs-cli --endpoint 127.0.0.1:8091 -w /etc/neofs/storage/wallet.json control set-status --status maintenance`

## Your Environment
* Version used:
`NeoFS Storage node
Version: v0.30.2
GoVersion: go1.17.11`
* Server setup and configuration:
Cloud hosting. VM: 4 CPU, 8 GB RAM.
* Operating System and version (`uname -a`):
`Linux glagoli 5.10.0-16-amd64 #1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux`

**Comment by anikeev-yadro** [comment]
Log from storage node:
`Aug 11 06:19:23 glagoli sudo[3387]:    admin : TTY=pts/0 ; PWD=/home/admin ; USER=root ; COMMAND=/usr/bin/neofs-cli --endpoint 1
27.0.0.1:8091 -w /etc/neofs/storage/wallet.json control set-status --status maintenance
Aug 11 06:19:23 glagoli sudo[3387]: pam_unix(sudo:session): session opened for user root(uid=0) by admin(uid=1000)
Aug 11 06:19:23 glagoli neogo-morph-cn[389]: 2022-08-11T06:19:23.867Z        INFO        persisted to disk        {"blocks": 1,
"keys": 41, "headerHeight": 26836, "blockHeight": 26836, "took": "5.880464ms"}
Aug 11 06:19:24 glagoli neofs-node[926]: panic: close of closed channel
Aug 11 06:19:24 glagoli neofs-node[926]: goroutine 603546 [running]:
Aug 11 06:19:24 glagoli neofs-node[926]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache.(*cache).Close(0xc0
003f2ea0)
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/writecache/writecache.
go:160 +0x3d
Aug 11 06:19:24 glagoli neofs-node[926]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/shard.(*Shard).Close(0xc00026c
be0)
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/shard/control.go:234 +
0x2c9
Aug 11 06:19:24 glagoli neofs-node[926]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine.(*StorageEngine).close(
0xc00026cb90, 0x10)
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine/control.go:118
+0x1ab
Aug 11 06:19:24 glagoli neofs-node[926]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine.(*StorageEngine).setBlo
ckExecErr(0xc00026cb90, {0x1219500, 0xc0000b5c10})
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine/control.go:167
+0x11b
Aug 11 06:19:24 glagoli neofs-node[926]: github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine.(*StorageEngine).BlockE
xecution(...)
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/pkg/local_object_storage/engine/control.go:187
Aug 11 06:19:24 glagoli neofs-node[926]: main.(*cfg).SetNetmapStatus(0xc00000e508, 0x1231c48)
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/netmap.go:323 +0x28d
Aug 11 06:19:24 glagoli neofs-node[926]: github.com/nspcc-dev/neofs-node/pkg/services/control/server.(*Server).SetNetmapStatus(0
xc00000e508, {0xc00156f240, 0x5dd366}, 0xc00156f240)
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/pkg/services/control/server/set_netmap_status.g
o:21 +0x76
Aug 11 06:19:24 glagoli neofs-node[926]: github.com/nspcc-dev/neofs-node/pkg/services/control._ControlService_SetNetmapStatus_Ha
ndler({0x1024dc0, 0xc00000e508}, {0x123c078, 0xc0001a3440}, 0xc00167b3e0, 0x0)
Aug 11 06:19:24 glagoli neofs-node[926]:         github.com/nspcc-dev/neofs-node/pkg/services/control/service_grpc.pb.go:243 +0x
170
Aug 11 06:19:24 glagoli neofs-node[926]: google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000c28c0, {0x1250ae0, 0xc000ae6180
}, 0xc000ada360, 0xc001cac060, 0x1acf350, 0x0)
Aug 11 06:19:24 glagoli neofs-node[926]:         google.golang.org/grpc@v1.41.0/server.go:1279 +0xccf
Aug 11 06:19:24 glagoli neofs-node[926]: google.golang.org/grpc.(*Server).handleStream(0xc0000c28c0, {0x1250ae0, 0xc000ae6180},
0xc000ada360, 0x0)
Aug 11 06:19:24 glagoli neofs-node[926]:         google.golang.org/grpc@v1.41.0/server.go:1608 +0xa2a
Aug 11 06:19:24 glagoli neofs-node[926]: google.golang.org/grpc.(*Server).serveStreams.func1.2()
Aug 11 06:19:24 glagoli neofs-node[926]:         google.golang.org/grpc@v1.41.0/server.go:923 +0x98
Aug 11 06:19:24 glagoli neofs-node[926]: created by google.golang.org/grpc.(*Server).serveStreams.func1
Aug 11 06:19:24 glagoli neofs-node[926]:         google.golang.org/grpc@v1.41.0/server.go:921 +0x294
Aug 11 06:19:24 glagoli systemd[1]: neofs-storage.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 11 06:19:24 glagoli systemd[1]: neofs-storage.service: Failed with result 'exit-code'.
Aug 11 06:19:24 glagoli systemd[1]: neofs-storage.service: Consumed 3d 1h 17min 3.673s CPU time.
Aug 11 06:19:24 glagoli sudo[3387]: pam_unix(sudo:session): session closed for user root
Aug 11 06:19:29 glagoli systemd[1]: neofs-storage.service: Scheduled restart job, restart counter is at 4.
Aug 11 06:19:29 glagoli systemd[1]: Stopped NeoFS Storage node.
Aug 11 06:19:29 glagoli systemd[1]: neofs-storage.service: Consumed 3d 1h 17min 3.673s CPU time.`
