### ISSUE TITLE
Lot of panics in neofs-ir when run autotests

### ISSUE THREAD

**Issue by anikeev-yadro** [nspcc-dev/neofs-node#2081]
We have a lot of panics in neofs-ir when run autotests:
```
Nov 21 11:37:36 az neofs-ir[15476]: 2022/11/21 11:37:36 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
Nov 21 11:37:36 az neofs-ir[15476]: 2022/11/21 11:37:36 worker exits from panic: goroutine 12426 [running]:
Nov 21 11:37:36 az neofs-ir[15476]: github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/panjf2000/ants/v2@v2.4.0/worker.go:58 +0x10c
Nov 21 11:37:36 az neofs-ir[15476]: panic({0xd58320, 0x16a12b0})
Nov 21 11:37:36 az neofs-ir[15476]:         runtime/panic.go:838 +0x207
Nov 21 11:37:36 az neofs-ir[15476]: math/big.(*Int).Bytes(0x0)
Nov 21 11:37:36 az neofs-ir[15476]:         math/big/int.go:453 +0x1d
Nov 21 11:37:36 az neofs-ir[15476]: crypto/ecdsa.Sign({0xfe79a0, 0xc00003a8d0}, 0xc00043c318, {0xc000314fd0, 0x40, 0x40})
Nov 21 11:37:36 az neofs-ir[15476]:         crypto/ecdsa/ecdsa.go:217 +0xfa
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-crypto.SignHash(0xc00043c318, {0xc000314fd0?, 0x42a2a71260b5afb0?, 0xdb2ee479746f5a8e?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-crypto@v0.4.0/ecdsa.go:185 +0x47
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-crypto.Sign(0xb81022?, {0xc0005a0cc0?, 0xc0005a0cc0?, 0xd0b040?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-crypto@v0.4.0/ecdsa.go:180 +0x89
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/util/signature.sign(0xc000591100?, 0xff1628?, {0xc0005a0cc0?, 0xc00165f330?, 0x0?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/util/signature/options.go:53 +0x165
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/util/signature.SignDataWithHandler(0xc00043c318, {0xff1628, 0xc00165f330}, 0xc000315150, {0x0, 0x0, 0xc000315160?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/util/signature/data.go:43 +0xe6
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/signature.signServiceMessagePart(0xe12700?, {0xfefb98?, 0xc0005bc1b0}, 0xc000315280)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/signature/sign.go:200 +0xb9
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/signature.SignServiceMessage(0xc00043c310?, {0xe12700?, 0xc00130abb8})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/signature/sign.go:172 +0x36c
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-sdk-go/client.(*Client).ObjectHash(0xc00043c310, {0xff4be0, 0xc00059e7e0}, {{0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.7/client/object_hash.go:179 +0x185
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).ObjectHash.func1({0xffa2d8?, 0xc00043c310?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:179 +0x9c
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).iterateClients.func1({{0xffac60?, 0xc00130ab40?}})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:108 +0xc9
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network.AddressGroup.IterateAddresses(...)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/group.go:37
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).iterateClients(0x7f7f4be97d38?, {0xff4be0?, 0xc00059e7e0?}, 0x10?)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:96 +0xbb
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).ObjectHash(0xc0014d1ec0?, {0xff4be0?, 0xc00059e7e0?}, {{0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:178 +0x87
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client.Client.HashPayloadRange({0xc000254150?, {0xffa260?, 0xc0014d1ec0?}}, {{{{0xff4be0, 0xc00059e7e0}}, {{{...}, {...}}}}, 0xc000599010})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client/client.go:308 +0x345
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client.HashObjectRange({0xff4be0?, 0xc00059e7e0?}, {0xc000254150?, {0xffa260?, 0xc0014d1ec0?}}, {{0x92, 0x76, 0xb2, 0xd4, 0xb4, ...}, ...}, ...)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client/client.go:338 +0x105
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/innerring.(*ClientCache).GetRangeHash(0xc000235940, {{{0xff4b70, 0xc00152d380}, {{{...}, {...}, {...}, 0x1}}, {0xf2, 0x75, 0x79, ...}, ...}, ...})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/innerring/rpc.go:192 +0x385
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor.(*Context).collectHashes.func1({{{0xc000566360, 0x21, 0x30}, {0xc0016c10c0, 0x2, 0x2}, {0xc00017ae00, 0x9, 0x9}, 0x1}}, ...)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor/pdp.go:141 +0x3e4
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor.(*Context).collectHashes(0xc00053d1f8?, 0xc000122360)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor/pdp.go:155 +0xbe
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor.(*Context).processPair(0xc0005a0c00?, 0xc0005adfa8?)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-nod
Nov 21 11:37:36 az neofs-ir[15476]: 2022/11/21 11:37:36 worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
Nov 21 11:37:36 az neofs-ir[15476]: 2022/11/21 11:37:36 worker exits from panic: goroutine 12425 [running]:
Nov 21 11:37:36 az neofs-ir[15476]: github.com/panjf2000/ants/v2.(*goWorker).run.func1.1()
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/panjf2000/ants/v2@v2.4.0/worker.go:58 +0x10c
Nov 21 11:37:36 az neofs-ir[15476]: panic({0xd58320, 0x16a12b0})
Nov 21 11:37:36 az neofs-ir[15476]:         runtime/panic.go:838 +0x207
Nov 21 11:37:36 az neofs-ir[15476]: math/big.(*Int).Bytes(0x0)
Nov 21 11:37:36 az neofs-ir[15476]:         math/big/int.go:453 +0x1d
Nov 21 11:37:36 az neofs-ir[15476]: crypto/ecdsa.Sign({0xfe79a0, 0xc00003a8d0}, 0xc000130238, {0xc000314fd0, 0x40, 0x40})
Nov 21 11:37:36 az neofs-ir[15476]:         crypto/ecdsa/ecdsa.go:217 +0xfa
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-crypto.SignHash(0xc000130238, {0xc000314fd0?, 0x236caf14af36056b?, 0xc906625b44c444f9?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-crypto@v0.4.0/ecdsa.go:185 +0x47
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-crypto.Sign(0xb81022?, {0xc0005a0de0?, 0xc0005a0de0?, 0xd0b040?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-crypto@v0.4.0/ecdsa.go:180 +0x89
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/util/signature.sign(0xc000591180?, 0xff1628?, {0xc0005a0de0?, 0xc00165f3b0?, 0x0?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/util/signature/options.go:53 +0x165
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/util/signature.SignDataWithHandler(0xc000130238, {0xff1628, 0xc00165f3b0}, 0xc000315150, {0x0, 0x0, 0xc000315160?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/util/signature/data.go:43 +0xe6
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/signature.signServiceMessagePart(0xe12700?, {0xfefb98?, 0xc0005bc260}, 0xc000315280)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/signature/sign.go:200 +0xb9
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-api-go/v2/signature.SignServiceMessage(0xc000130230?, {0xe12700?, 0xc00130ac78})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-api-go/v2@v2.14.0/signature/sign.go:172 +0x36c
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-sdk-go/client.(*Client).ObjectHash(0xc000130230, {0xff4be0, 0xc00059e840}, {{0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-sdk-go@v1.0.0-rc.7/client/object_hash.go:179 +0x185
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).ObjectHash.func1({0xffa2d8?, 0xc000130230?})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:179 +0x9c
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).iterateClients.func1({{0xffac60?, 0xc00130ac00?}})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:108 +0xc9
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network.AddressGroup.IterateAddresses(...)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/group.go:37
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).iterateClients(0x7f7f4be97d38?, {0xff4be0?, 0xc00059e840?}, 0x10?)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:96 +0xbb
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/network/cache.(*multiClient).ObjectHash(0xc0000ef380?, {0xff4be0?, 0xc00059e840?}, {{0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, 0x0, ...}, ...})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/network/cache/multi.go:178 +0x87
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client.Client.HashPayloadRange({0xc000254150?, {0xffa260?, 0xc0000ef380?}}, {{{{0xff4be0, 0xc00059e840}}, {{{...}, {...}}}}, 0xc000598f30})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client/client.go:308 +0x345
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client.HashObjectRange({0xff4be0?, 0xc00059e840?}, {0xc000254150?, {0xffa260?, 0xc0000ef380?}}, {{0x92, 0x76, 0xb2, 0xd4, 0xb4, ...}, ...}, ...)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/innerring/internal/client/client.go:338 +0x105
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/innerring.(*ClientCache).GetRangeHash(0xc000235940, {{{0xff4b70, 0xc00152d380}, {{{...}, {...}, {...}, 0x1}}, {0x58, 0xb5, 0x12, ...}, ...}, ...})
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/innerring/rpc.go:192 +0x385
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor.(*Context).collectHashes.func1({{{0xc0005663c0, 0x21, 0x30}, {0xc0016c1140, 0x2, 0x2}, {0xc00017b200, 0x9, 0x9}, 0x1}}, ...)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor/pdp.go:141 +0x3e4
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor.(*Context).collectHashes(0xc00059e718?, 0xc000122240)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor/pdp.go:155 +0xbe
Nov 21 11:37:36 az neofs-ir[15476]: github.com/nspcc-dev/neofs-node/pkg/services/audit/auditor.(*Context).processPair(0xc0005a0ba0?, 0xc000012fa8?)
Nov 21 11:37:36 az neofs-ir[15476]:         github.com/nspcc-dev/neofs-nod
```

## Steps to Reproduce (for bugs)
Panic occurred when those tests have run:
testsuites.container.test_container#test_container_creation
testsuites.container.test_container#test_container_creation_deletion_parallel
testsuites.object.test_object_lifetime#test_object_api_lifetime
testsuites.object.test_object_api#test_object_search_should_return_tombstone_items

**Nodes logs:** [d02e51b89cd4d99.zip](https://github.com/nspcc-dev/neofs-node/files/10058334/d02e51b89cd4d99.zip)
**Tests console log:** [consoleText.zip](https://github.com/nspcc-dev/neofs-node/files/10058347/consoleText.zip)

**Version:**
```
NeoFS Node 0.34.0-60-g02049ca5-dirty
```
##Your Environment
Server setup and configuration:
cloud, 4 VMs, 4 SN, 4 http qw, 4 s3 gw

Operating System and version (uname -a):
linux vedi 5.10.0-16-amd64 https://github.com/nspcc-dev/neofs-node/issues/1 SMP Debian 5.10.127-1 (2022-06-30) x86_64 GNU/Linux

**Comment by carpawell** [comment]
Closed via #2082.
