### ISSUE TITLE
neofs-node breaks after update to 0.44.0

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-node#3034]
```
systemd[1]: Started neofs-storage.service - NeoFS Storage node.
neofs-node[182252]: panic: unable to decode config: 1 error(s) decoding:
neofs-node[182252]: * 'node[<interface {} Value>]' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[exit_zero:false]'
neofs-node[182252]: goroutine 1 [running]:
neofs-node[182252]: github.com/nspcc-dev/neofs-node/cmd/neofs-node/config.New({}, {0xc00021ff08, 0x1, 0x5?})
neofs-node[182252]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/config/config.go:61 +0x273
neofs-node[182252]: main.main()
neofs-node[182252]:         github.com/nspcc-dev/neofs-node/cmd/neofs-node/main.go:47 +0x27b
systemd[1]: neofs-storage.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
systemd[1]: neofs-storage.service: Failed with result 'exit-code'.
```

**Comment by roman-khimov** [comment]
The problem is broken configuration. Error message can be improved.

**Comment by roman-khimov** [comment]
Specifically
```
  subnet:
    exit_zero: false
```
in `node`.
